### ISSUE TITLE
Bump [compat] MLJModelInterface="^0.1,^0.2"

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJLinearModels.jl#55]
Here the changes since 0.1.8, which I doubt break anything in MLJLinearModels:

- Bring in `is_same_except` and similar gizmos from MLJBase;  see https://github.com/alan-turing-institute/MLJBase.jl/issues/178

- Let all models share same traits (#19, https://github.com/alan-turing-institute/MLJBase.jl/issues/163)

- Add `save` and `restore` stubs for serialisation

**Comment by tlienart** [comment]
done
