### ISSUE TITLE
schema(X) fails

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJLinearModels.jl#69]
at https://github.com/alan-turing-institute/MLJLinearModels.jl/blob/master/src/mlj/interface.jl#L22 the function `schema(X)` fails. @tlienart

**Comment by tlienart** [comment]
Thanks I'll try  to fix that  asap

**Comment by tlienart** [comment]
yeah that's a shortcircuit that's buggy, I think that's a recent PR that I  hadn't properly tested

**Comment by OkonSamuel** [comment]
> yeah that's a shortcircuit that's buggy, I think that's a recent PR that I hadn't properly tested

I guess the `MMI.schema` method isn't extended

**Comment by tlienart** [comment]
What code did you use that threw this bug?

**Comment by OkonSamuel** [comment]
`MMI.schema(X)`. This threw the following error.
```julia
ERROR: MethodError: no method matching schema(::MLJModelInterface.FullInterface, ::Val{:table}, ::Tables.MatrixTable{Array{Float64,2}})
```

**Comment by tlienart** [comment]
hmm that should work, do you have the latest version of MLJBase?

**Comment by tlienart** [comment]
I just did:

```
julia> MLJBase.MMI.schema(Xt)
┌─────────┬─────────┬────────────────────────────┐
│ _.names │ _.types │ _.scitypes                 │
├─────────┼─────────┼────────────────────────────┤
│ x1      │ Float64 │ ScientificTypes.Continuous │
│ x2      │ Float64 │ ScientificTypes.Continuous │
│ x3      │ Float64 │ ScientificTypes.Continuous │
│ x4      │ Float64 │ ScientificTypes.Continuous │
│ x5      │ Float64 │ ScientificTypes.Continuous │
└─────────┴─────────┴────────────────────────────┘
_.nrows = 100
```

**Comment by OkonSamuel** [comment]
Okay. Let me check

**Comment by OkonSamuel** [comment]
@tlienart. It works

**Comment by OkonSamuel** [comment]
@tlienart. I just tested the master branch of this repo with `nthreads=2` on `MLJ.evaluate` and `MLJ.tunedmodel`. It works perfectly. No issues.

**Comment by tlienart** [comment]
awesome thanks!
