### ISSUE TITLE
throw error much ealier for LogisticClassifier 

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJLinearModels.jl#71]
@tlienart . Sorry to disturb you again. I think a more informative error message should be thrown.
I ran `LogisticClassifier` using the default values on a dataset having `nclasses > 2`. it thows the following Error
```julia
ERROR: DimensionMismatch("new dimensions (4, 4) must be consistent with array size 4")
```
Although setting `multi_class=true` works. i think there should be a more informative error message.

**Comment by tlienart** [comment]
right , I'll get on to that :+1: it should just work
