### ISSUE TITLE
Don't expose `multiclass` and `nclasses`

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJLinearModels.jl#76]
@tlienart  Currently you expose `multiclass` and `nclasses` parameter to the user and you mutate these parameters in `MMI.fit` method depending on the data.
I think this violates MLJ assumption that model hyperparameters should not be mutated during fitting. 
I think it's better not to expose these hyparameters in model struct (you can still set them internally though)

**Comment by OkonSamuel** [comment]
@tlienart  could you tag a new release. Am writing a tutorial using this package

**Comment by tlienart** [comment]
Oh I thought I did?

**Comment by tlienart** [comment]
Yeah 0.5 does this
