### ISSUE TITLE
dev branch woes 

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJLinearModels.jl#83]
@tlienart 

I tried pushing something to dev but discovered post facto that it was not in sync with master. There are a lot of merge conflicts to resolve when I try to sync. It looks like a number of PR's may have been merged directly onto master. 

I propose deleting dev and starting over, trusting to current master. There appear to be no commits on master since last patch. 

Can you confirm this is okay, thanks.

**Comment by DilumAluthge** [comment]
In the future, it might be easier to set `dev` as the default branch for this repo. That way, when someone opens a PR, GitHub will set `dev` as the target branch of the PR by default.

This might help reduce the frequency of people accidentally merging PRs onto `master` when they should have merged into `dev`.

Instructions here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/changing-the-default-branch#changing-the-default-branch

**Comment by tlienart** [comment]
@ablaom sure 👍🏼

**Comment by tlienart** [comment]
alright, I cleaned up old stale branches, brought in #83 (update to TagBot) and synced the dev branch. Let me know if there's something more I can do!

**Comment by tlienart** [comment]
ah and following @DilumAluthge 's suggestion I made `dev` the default branch.

**Comment by tlienart** [comment]
looks like I have a bit more work to do some tests are failing

**Comment by tlienart** [comment]
all fixed.
